# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/ADC_axi_smc_0.xci
# IP: The module: 'ADC_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/bd_61e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_10/bd_61e3_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_14/bd_61e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_18/bd_61e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_15/bd_61e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_16/bd_61e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_17/bd_61e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_11/bd_61e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_12/bd_61e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_13/bd_61e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_7/bd_61e3_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_8/bd_61e3_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_9/bd_61e3_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_2/bd_61e3_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_3/bd_61e3_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_4/bd_61e3_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_5/bd_61e3_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_6/bd_61e3_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_0/bd_61e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_10/bd_61e3_s02a2s_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_14/bd_61e3_m00s2a_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_15/bd_61e3_m00awn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_16/bd_61e3_m00wn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_17/bd_61e3_m00bn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_11/bd_61e3_sawn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_12/bd_61e3_swn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_13/bd_61e3_sbn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_2/bd_61e3_arsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_3/bd_61e3_rsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_4/bd_61e3_awsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_5/bd_61e3_wsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_6/bd_61e3_bsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/ADC_axi_smc_0.xci
# IP: The module: 'ADC_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/bd_61e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_10/bd_61e3_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_14/bd_61e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_18/bd_61e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_15/bd_61e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_16/bd_61e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_17/bd_61e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_11/bd_61e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_12/bd_61e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_13/bd_61e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_7/bd_61e3_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_8/bd_61e3_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_9/bd_61e3_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_2/bd_61e3_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_3/bd_61e3_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_4/bd_61e3_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_5/bd_61e3_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_6/bd_61e3_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_0/bd_61e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_10/bd_61e3_s02a2s_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_14/bd_61e3_m00s2a_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_15/bd_61e3_m00awn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_16/bd_61e3_m00wn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_17/bd_61e3_m00bn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_11/bd_61e3_sawn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_12/bd_61e3_swn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_13/bd_61e3_sbn_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_2/bd_61e3_arsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_3/bd_61e3_rsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_4/bd_61e3_awsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_5/bd_61e3_wsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_6/bd_61e3_bsw_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/bd_0/ip/ip_1/bd_61e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
