#set_property IOSTANDARD LVCMOS18 [get_ports {D0A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D1A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D2A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D3A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D4A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D5A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D6A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D7A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D8A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D9A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D10A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D11A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D12A}]
#set_property IOSTANDARD LVCMOS18 [get_ports {D13A}]
#set_property IOB TRUE [get_ports {D1A}]
#set_property IOB TRUE [get_ports {D2A}]
#set_property IOB TRUE [get_ports {D3A}]
#set_property IOB TRUE [get_ports {D4A}]
#set_property IOB TRUE [get_ports {D5A}]
#set_property IOB TRUE [get_ports {D6A}]
#set_property IOB TRUE [get_ports {D7A}]
#set_property IOB TRUE [get_ports {D8A}]
#set_property IOB TRUE [get_ports {D9A}]
#set_property IOB TRUE [get_ports {D10A}]
#set_property IOB TRUE [get_ports {D11A}]
#set_property IOB TRUE [get_ports {D12A}]
#set_property IOB TRUE [get_ports {D13A}]
#set_property IOB TRUE [get_ports {D0A}]
##set_property IOSTANDARD LVCMOS33 [get_ports {CS}]
#set_property PACKAGE_PIN Y17 [get_ports {D0A}]
#set_property PACKAGE_PIN W16 [get_ports {D1A}]
#set_property PACKAGE_PIN Y16 [get_ports {D2A}]
#set_property PACKAGE_PIN W15 [get_ports {D3A}]
#set_property PACKAGE_PIN W14 [get_ports {D4A}]
#set_property PACKAGE_PIN Y14 [get_ports {D5A}]
#set_property PACKAGE_PIN W13 [get_ports {D6A}]
#set_property PACKAGE_PIN V12 [get_ports {D7A}]
#set_property PACKAGE_PIN V13 [get_ports {D8A}]
#set_property PACKAGE_PIN T14 [get_ports {D9A}]
#set_property PACKAGE_PIN T15 [get_ports {D10A}]
#set_property PACKAGE_PIN V15 [get_ports {D11A}]
#set_property PACKAGE_PIN T16 [get_ports {D12A}]
#set_property PACKAGE_PIN V16 [get_ports {D13A}]
##set_property PACKAGE_PIN V18 [get_ports {CS}]

##Clocks
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports clk_p]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports clk_n]
#set_property PACKAGE_PIN U18 [get_ports clk_p]
#set_property PACKAGE_PIN U19 [get_ports clk_n]

#DAC
# data

set_property IOSTANDARD LVCMOS33 [get_ports {dac_dat_o[*]}]
set_property SLEW SLOW [get_ports {dac_dat_o[*]}]
set_property DRIVE 4 [get_ports {dac_dat_o[*]}]
# set_property IOB TRUE [get_ports {dac_dat_o[*]}]

set_property PACKAGE_PIN M19 [get_ports {dac_dat_o[0]}]
set_property PACKAGE_PIN M20 [get_ports {dac_dat_o[1]}]
set_property PACKAGE_PIN L19 [get_ports {dac_dat_o[2]}]
set_property PACKAGE_PIN L20 [get_ports {dac_dat_o[3]}]
set_property PACKAGE_PIN K19 [get_ports {dac_dat_o[4]}]
set_property PACKAGE_PIN J19 [get_ports {dac_dat_o[5]}]
set_property PACKAGE_PIN J20 [get_ports {dac_dat_o[6]}]
set_property PACKAGE_PIN H20 [get_ports {dac_dat_o[7]}]
set_property PACKAGE_PIN G19 [get_ports {dac_dat_o[8]}]
set_property PACKAGE_PIN G20 [get_ports {dac_dat_o[9]}]
set_property PACKAGE_PIN F19 [get_ports {dac_dat_o[10]}]
set_property PACKAGE_PIN F20 [get_ports {dac_dat_o[11]}]
set_property PACKAGE_PIN D20 [get_ports {dac_dat_o[12]}]
set_property PACKAGE_PIN D19 [get_ports {dac_dat_o[13]}]

# control

set_property IOSTANDARD LVCMOS33 [get_ports dac_*_o]
set_property SLEW FAST [get_ports dac_*_o]
set_property DRIVE 8 [get_ports dac_*_o]

set_property PACKAGE_PIN M17 [get_ports dac_wrt_o]
set_property PACKAGE_PIN N16 [get_ports dac_sel_o]
set_property PACKAGE_PIN M18 [get_ports dac_clk_o]
set_property PACKAGE_PIN N15 [get_ports dac_rst_o]