# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0.xci
# IP: The module: 'ADC_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0.xci
# IP: The module: 'ADC_rst_ps7_0_125M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_rst_ps7_0_125M_0/ADC_rst_ps7_0_125M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_rst_ps7_0_125M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
