webtalk_init -webtalk_dir D:\\NextLab\\Vivado\\redpitaya_Practice\\redpitaya_Practice.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-29 14:39:00" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4i53ofo5s5qb40ntla87v4hmr1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_54" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "54" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.047 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1527615044953" -context "sdk\\\\bsp/1527615044953"
webtalk_add_data -client sdk -key hwid -value "1527102388496" -context "sdk\\\\bsp/1527615044953"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1527615044953"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1527615044953"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1527615044953"
webtalk_add_data -client sdk -key uid -value "1527615052866" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key hwid -value "1527102388496" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key bspid -value "1527615044953" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key projSize -value "299.859375" -context "sdk\\\\application/1527615052866"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key DebugCount -value "3" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1527619140030"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1527619140030"
webtalk_transmit -clientid 2677411221 -regid "" -xml D:\\NextLab\\Vivado\\redpitaya_Practice\\redpitaya_Practice.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\NextLab\\Vivado\\redpitaya_Practice\\redpitaya_Practice.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\NextLab\\Vivado\\redpitaya_Practice\\redpitaya_Practice.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
