# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/ADC_system_ila_0_0.xci
# IP: The module: 'ADC_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/bd_d9b3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d9b3 || ORIG_REF_NAME==bd_d9b3} -quiet] -quiet

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/bd_d9b3_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/ADC_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/bd_d9b3_ila_lib_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/bd_d9b3_ooc.xdc

# IP: D:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/ADC_system_ila_0_0.xci
# IP: The module: 'ADC_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/bd_d9b3.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d9b3 || ORIG_REF_NAME==bd_d9b3} -quiet] -quiet

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/bd_d9b3_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/ADC_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADC_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d9b3_ila_lib_0 || ORIG_REF_NAME==bd_d9b3_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/ip/ip_0/bd_d9b3_ila_lib_0_ooc.xdc

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/ADC/ip/ADC_system_ila_0_0/bd_0/bd_d9b3_ooc.xdc
