# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0.xci
# IP: The module: 'DAC_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0.xci
# IP: The module: 'DAC_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/NextLab/Vivado/redpitaya_Practice/redpitaya_Practice.srcs/sources_1/bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAC_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
