# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Pin_out.xdc

# Block Designs: bd/DAC/DAC.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC || ORIG_REF_NAME==DAC} -quiet] -quiet

# IP: bd/DAC/ip/DAC_processing_system7_0_0/DAC_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_processing_system7_0_0 || ORIG_REF_NAME==DAC_processing_system7_0_0} -quiet] -quiet

# IP: bd/DAC/ip/DAC_dds_compiler_0_0/DAC_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_dds_compiler_0_0 || ORIG_REF_NAME==DAC_dds_compiler_0_0} -quiet] -quiet

# IP: bd/DAC/ip/DAC_axis_red_pitaya_dac_0_0/DAC_axis_red_pitaya_dac_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_axis_red_pitaya_dac_0_0 || ORIG_REF_NAME==DAC_axis_red_pitaya_dac_0_0} -quiet] -quiet

# IP: bd/DAC/ip/DAC_ila_0_0/DAC_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_ila_0_0 || ORIG_REF_NAME==DAC_ila_0_0} -quiet] -quiet

# IP: bd/DAC/ip/DAC_clk_wiz_0/DAC_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DAC_clk_wiz_0 || ORIG_REF_NAME==DAC_clk_wiz_0} -quiet] -quiet

# XDC: bd/DAC/DAC_ooc.xdc
